[package]
name = 'arcpbf'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = "1.95"

[lib]
crate-type = ['staticlib']
name = 'arcpbf'

[dependencies]
extendr-api = "0.9.0"
esripbf = { path = "/Users/josi/github/serde_esri/esripbf", features = ["geoarrow"] }
arrow_extendr = { path = "/Users/josi/github/arrow-extendr" }
arrow-array = "59"
prost = "0.12.1"
anyhow = "1"

[profile.release]

codegen-units = 1
lto = true

[dev-dependencies]
extendr-engine = "0.9.0"
