# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib arcpbf, .registration = TRUE
NULL

read_pbf_ <- function(path) .Call(wrap__read_pbf_, path)

#' Read a pbf file as a raw vector
#'
#' @param path the path to the `.pbf` file.
#'
#' @returns a raw vector
#' @export
#' @examples
#' count_fp <- system.file("count.pbf", package = "arcpbf")
#' oid_fp <- system.file("ids.pbf", package = "arcpbf")
#' tbl_fp <- system.file("small-table.pbf", package = "arcpbf")
#' fc_fp <- system.file("small-points.pbf", package = "arcpbf")
#' count_raw <- open_pbf(count_fp)
#' oid_raw <- open_pbf(oid_fp)
#' tbl_raw <- open_pbf(tbl_fp)
#' fc_raw <- open_pbf(fc_fp)
open_pbf <- function(path) .Call(wrap__open_pbf, path)

#' Process a FeatureCollection PBF
#'
#' Process a pbf from a raw vector or a list of raw vectors.
#'
#' @param proto either a raw vector or a list of raw vectors containing a FeatureCollection pbf
#'
#' @details
#'
#' There are four types of PBF FeatureCollection responses that may be
#' returned.
#'
#' ### Feature Result
#'
#' In the case the PBF is a `FeatureResult` and `use_sf = FALSE`, a `data.frame`
#' is returned with the spatial reference stored in the `crs` attribute.
#' Otherwise an `sf` object is returned.
#'
#' ### Count Result
#'
#' The PBF can also return a count result, for example if the [query parameter](https://developers.arcgis.com/rest/services-reference/enterprise/query-feature-service-layer-.htm)
#' `returnCountOnly` is set to `true`. In this case, a scalar integer vector
#' is returned.
#'
#' ### Object ID Result
#'
#' In the case that the query parameter `returnIdsOnly` is `true`, a
#' `data.frame` is returned containing the object IDs and the column name
#' set to the object ID field name in the feature service.
#'
#' ### Extent Result
#'
#' When `returnExtentOnly` is `true`, a server may return an extent result. In this
#' case a named numeric vector of `xmin`, `ymin`, `xmax`, and `ymax` is returned
#' with the spatial reference in the `sr` attribute and the feature count, if
#' requested, in the `count` attribute. [`post_process_pbf()`] converts it to an
#' `sf` `bbox`.
#'
#' @returns
#'
#' - For count results, a scalar integer.
#' - For object ID results a `data.frame` with one column.
#' - For extent results a named numeric vector of class `pbf_extent`.
#' - For feature results, a `nanoarrow_array_stream` with a column per field and, for layers,
#'   a GeoArrow `geometry` column carrying the CRS.
#'
#' **Important**: Use [`post_process_pbf()`] to convert feature results to a `data.frame` or `sf` object.
#'
#' @export
#'
#' @examples
#' count_fp <- system.file("count.pbf", package = "arcpbf")
#' oid_fp <- system.file("ids.pbf", package = "arcpbf")
#' tbl_fp <- system.file("small-table.pbf", package = "arcpbf")
#' fc_fp <- system.file("small-points.pbf", package = "arcpbf")
#'
#' # count response
#' count_raw <- open_pbf(count_fp)
#' process_pbf(count_raw)
#'
#' # object id response
#' oid_raw <- open_pbf(oid_fp)
#' head(process_pbf(oid_raw))
#'
#' # table feature collection
#' tbl_raw <- open_pbf(tbl_fp)
#' process_pbf(tbl_raw)
#'
#' # feature collection with geometry
#' fc_raw <- open_pbf(fc_fp)
#' process_pbf(fc_raw)
process_pbf <- function(proto) .Call(wrap__process_pbf, proto)

multi_resp_process_ <- function(resps) .Call(wrap__multi_resp_process_, resps)

# nolint end
