# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_arcpbf_wrappers", use_symbols = TRUE, package_name = "arcpbf")

#' @docType package
#' @usage NULL
#' @useDynLib arcpbf, .registration = TRUE
NULL

#' @export
read_pbf <- function(path) .Call(wrap__read_pbf, path)

#' @export
open_pbf <- function(path) .Call(wrap__open_pbf, path)

#' @export
process_pbf <- function(proto) .Call(wrap__process_pbf, proto)


# nolint end
